<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\ScfPlatform.BuildingBlocks.Application\ScfPlatform.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\ScfPlatform.Modules.Iam.Contracts\ScfPlatform.Modules.Iam.Contracts.csproj" />
    <ProjectReference Include="..\ScfPlatform.Modules.Iam.Domain\ScfPlatform.Modules.Iam.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Provisioning\" />
    <Folder Include="Provisioning\" />
  </ItemGroup>

</Project>
