// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScfPlatform.Modules.Iam.Infrastructure.Persistence;

#nullable disable

namespace ScfPlatform.Modules.Iam.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IamDbContext))]
    partial class IamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("iam")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScfPlatform.BuildingBlocks.Infrastructure.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EventId");

                    b.Property<DateTime>("ProcessedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ProcessedOnUtc");

                    b.HasKey("EventId");

                    b.ToTable("InboxMessages", "iam");
                });

            modelBuilder.Entity("ScfPlatform.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Content");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("OccurredOnUtc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ProcessedOnUtc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("ProcessedOnUtc");

                    b.ToTable("OutboxMessages", "iam");
                });

            modelBuilder.Entity("ScfPlatform.Modules.Iam.Domain.Aggregates.DeactivationCascadeRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DeadlineUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeadlineUtc");

                    b.Property<string>("ReceivedSignals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReceivedSignals");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("StartedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartedOnUtc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("DeactivationCascadeRuns", "iam");
                });

            modelBuilder.Entity("ScfPlatform.Modules.Iam.Domain.Aggregates.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("AttemptCount");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodeHash");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiresOnUtc");

                    b.Property<DateTime>("IssuedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("IssuedOnUtc");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int")
                        .HasColumnName("MaxAttempts");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Purpose");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserAccountId");

                    b.Property<DateTime?>("VerifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("VerifiedOnUtc");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "Purpose");

                    b.ToTable("OtpChallenges", "iam");
                });

            modelBuilder.Entity("ScfPlatform.Modules.Iam.Domain.Aggregates.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("ActivatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActivatedOnUtc");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOnUtc");

                    b.Property<DateTime?>("DeactivatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeactivatedOnUtc");

                    b.Property<bool>("IdentityVerified")
                        .HasColumnType("bit")
                        .HasColumnName("IdentityVerified");

                    b.Property<string>("PasswordHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordHistory");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Permissions");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Role");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Status");

                    b.Property<string>("SuspendedReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SuspendedReason");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedOnUtc");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.HasIndex("Status");

                    b.ToTable("UserAccounts", "iam");
                });

            modelBuilder.Entity("ScfPlatform.Modules.Iam.Domain.Entities.AdminActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ActionType");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AdminUserId");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("OccurredOnUtc");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Reason");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TargetUserId");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("OccurredOnUtc");

                    b.HasIndex("TargetUserId");

                    b.ToTable("AdminActionLog", "iam");
                });

            modelBuilder.Entity("ScfPlatform.Modules.Iam.Infrastructure.Persistence.RevokedTokenRecord", b =>
                {
                    b.Property<string>("TokenIdOrRefreshHash")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TokenIdOrRefreshHash");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiresOnUtc");

                    b.Property<DateTime>("RevokedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("RevokedOnUtc");

                    b.HasKey("TokenIdOrRefreshHash");

                    b.ToTable("RevokedTokenRecords", "iam");
                });

            modelBuilder.Entity("ScfPlatform.Modules.Iam.Domain.Aggregates.UserAccount", b =>
                {
                    b.OwnsMany("ScfPlatform.Modules.Iam.Domain.Entities.BackupCode", "BackupCodes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Id");

                            b1.Property<string>("CodeHash")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CodeHash");

                            b1.Property<DateTime?>("UsedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("UsedOnUtc");

                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("UserAccountId");

                            b1.ToTable("BackupCodes", "iam");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsMany("ScfPlatform.Modules.Iam.Domain.Entities.PasswordResetToken", "PasswordResetTokens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Id");

                            b1.Property<DateTime>("ExpiresOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExpiresOnUtc");

                            b1.Property<DateTime>("IssuedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("IssuedOnUtc");

                            b1.Property<string>("TokenHash")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("TokenHash");

                            b1.Property<DateTime?>("UsedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("UsedOnUtc");

                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("TokenHash");

                            b1.HasIndex("UserAccountId");

                            b1.ToTable("PasswordResetTokens", "iam");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsMany("ScfPlatform.Modules.Iam.Domain.Entities.Session", "Sessions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Id");

                            b1.Property<string>("Channel")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Channel");

                            b1.Property<DateTime>("ExpiresOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExpiresOnUtc");

                            b1.Property<DateTime>("IssuedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("IssuedOnUtc");

                            b1.Property<DateTime>("LastSeenUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastSeenUtc");

                            b1.Property<string>("RefreshTokenHash")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("RefreshTokenHash");

                            b1.Property<DateTime?>("RevokedOnUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("RevokedOnUtc");

                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("RefreshTokenHash");

                            b1.HasIndex("UserAccountId");

                            b1.ToTable("Sessions", "iam");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");

                            b1.OwnsOne("ScfPlatform.Modules.Iam.Domain.ValueObjects.DeviceFingerprint", "DeviceFingerprint", b2 =>
                                {
                                    b2.Property<Guid>("SessionId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("DeviceFingerprint");

                                    b2.HasKey("SessionId");

                                    b2.ToTable("Sessions", "iam");

                                    b2.WithOwner()
                                        .HasForeignKey("SessionId");
                                });

                            b1.Navigation("DeviceFingerprint")
                                .IsRequired();
                        });

                    b.OwnsMany("ScfPlatform.Modules.Iam.Domain.Entities.TrustedDevice", "TrustedDevices", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Id");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Label");

                            b1.Property<DateTime>("TrustedUntilUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("TrustedUntilUtc");

                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("UserAccountId");

                            b1.ToTable("TrustedDevices", "iam");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");

                            b1.OwnsOne("ScfPlatform.Modules.Iam.Domain.ValueObjects.DeviceFingerprint", "DeviceFingerprint", b2 =>
                                {
                                    b2.Property<Guid>("TrustedDeviceId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("DeviceFingerprint");

                                    b2.HasKey("TrustedDeviceId");

                                    b2.ToTable("TrustedDevices", "iam");

                                    b2.WithOwner()
                                        .HasForeignKey("TrustedDeviceId");
                                });

                            b1.Navigation("DeviceFingerprint")
                                .IsRequired();
                        });

                    b.OwnsOne("ScfPlatform.Modules.Iam.Domain.ValueObjects.Credential", "Credential", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccounts", "iam");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");

                            b1.OwnsOne("ScfPlatform.Modules.Iam.Domain.ValueObjects.EmailAddress", "Email", b2 =>
                                {
                                    b2.Property<Guid>("CredentialUserAccountId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)")
                                        .HasColumnName("Email");

                                    b2.HasKey("CredentialUserAccountId");

                                    b2.HasIndex("Value")
                                        .IsUnique();

                                    b2.ToTable("UserAccounts", "iam");

                                    b2.WithOwner()
                                        .HasForeignKey("CredentialUserAccountId");
                                });

                            b1.OwnsOne("ScfPlatform.Modules.Iam.Domain.ValueObjects.MobileNumber", "Mobile", b2 =>
                                {
                                    b2.Property<Guid>("CredentialUserAccountId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)")
                                        .HasColumnName("Mobile");

                                    b2.HasKey("CredentialUserAccountId");

                                    b2.HasIndex("Value")
                                        .IsUnique();

                                    b2.ToTable("UserAccounts", "iam");

                                    b2.WithOwner()
                                        .HasForeignKey("CredentialUserAccountId");
                                });

                            b1.OwnsOne("ScfPlatform.Modules.Iam.Domain.ValueObjects.PasswordHash", "PasswordHash", b2 =>
                                {
                                    b2.Property<Guid>("CredentialUserAccountId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Algorithm")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("PasswordAlgorithm");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("PasswordHash");

                                    b2.HasKey("CredentialUserAccountId");

                                    b2.ToTable("UserAccounts", "iam");

                                    b2.WithOwner()
                                        .HasForeignKey("CredentialUserAccountId");
                                });

                            b1.Navigation("Email")
                                .IsRequired();

                            b1.Navigation("Mobile")
                                .IsRequired();

                            b1.Navigation("PasswordHash")
                                .IsRequired();
                        });

                    b.OwnsOne("ScfPlatform.Modules.Iam.Domain.ValueObjects.LockState", "LockState", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("FailedLoginCount")
                                .HasColumnType("int")
                                .HasColumnName("FailedLoginCount");

                            b1.Property<int>("FailedOtpCount")
                                .HasColumnType("int")
                                .HasColumnName("FailedOtpCount");

                            b1.Property<bool>("IsLocked")
                                .HasColumnType("bit")
                                .HasColumnName("IsLocked");

                            b1.Property<DateTime?>("LockedUntilUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("LockedUntilUtc");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccounts", "iam");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("ScfPlatform.Modules.Iam.Domain.ValueObjects.MfaConfiguration", "Mfa", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("bit")
                                .HasColumnName("Mfa_Enabled");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Mfa_Method");

                            b1.Property<string>("SecretRef")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Mfa_SecretRef");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccounts", "iam");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("BackupCodes");

                    b.Navigation("Credential")
                        .IsRequired();

                    b.Navigation("LockState")
                        .IsRequired();

                    b.Navigation("Mfa")
                        .IsRequired();

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Sessions");

                    b.Navigation("TrustedDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
