<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\ScfPlatform.BuildingBlocks.Application\ScfPlatform.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\ScfPlatform.BuildingBlocks.Domain\ScfPlatform.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\ScfPlatform.BuildingBlocks.Infrastructure\ScfPlatform.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\BC01-Iam\ScfPlatform.Modules.Iam.Api\ScfPlatform.Modules.Iam.Api.csproj" />
    <ProjectReference Include="..\..\Modules\BC01-Iam\ScfPlatform.Modules.Iam.Contracts\ScfPlatform.Modules.Iam.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\BC01-Iam\ScfPlatform.Modules.Iam.Infrastructure\ScfPlatform.Modules.Iam.Infrastructure.csproj" />
  </ItemGroup>

</Project>
